### ISSUE TITLE
Format not detected ( Error: failed to launch: determine start command: process type web was not found)

### ISSUE THREAD

**Issue by anthonydahanne** [heroku/java-buildpack#3]
Hello,
I'm using latest CNCF pack : 
```
 ~/pack version
v0.0.9 (git sha: a1a1a0eef63bd09136ab76663bdbc3b0ab3a4931)
```

and I tried to build a Jhipster project (bsed on spring boot, with some frontend java script.)
With the help of @jkutner on Slack, I could use the heroku buildpack to build an image

```
docker pull heroku/pack:18
docker pull heroku/pack:18-build
~/pack add-stack heroku-18 --build-image heroku/pack:18-build --run-image heroku/pack:18
~/pack build  --builder=heroku/buildpacks  image:tag --publish
```

The project I tried to build (https://github.com/ehcache/ehcache3-samples/tree/master/fullstack) had a war packaking format, so I switched it to jar, but still no luck; the pack is confused :  

```
[builder] [Releasing]
[builder] No process types detected
```
And running the image returns : 
```
 Error: failed to launch: determine start command: process type web was not found
```
Although , after looking at the produced image, the jar is there : 

```
root@6e1c159e2bb2:/workspace/app# ls target/
classes  demo-1.0.0-SNAPSHOT.jar  demo-1.0.0-SNAPSHOT.jar.original  dependencies.txt  generated-sources  generated-test-sources  maven-archiver  maven-status  test-classes
```

When using this project : git@github.com:heroku/java-getting-started.git , I correctly get : 

```
[builder] [Releasing]
[builder] Discovered process type(s):
[builder]   web: java -jar target/java-getting-started-1.0.jar
```

I expect the pack to correctly figure out what to use to run the container

**Comment by jkutner** [comment]
@anthonydahanne can you tell me (or show me a patch) for how you modified the `pom.xml` so that the buildpack worked with the monorepo? I'm not sure if I'm building my artifact the same was as you.

Also, can you inspect the contents of you jar/war file's `META-INF/MANIFEST.MF`? A command like this should do it:

```
$ unzip -p target/myapp.jar META-INF/MANIFEST.MF
```
